spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/carManagementDB?createDatabaseIfNotExist=true"
    username: "root"
    password: "!P@$$word1995"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB